/*

 GRASSLAND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : map_v1_1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GrasslandWidth 20
#define GrasslandHeight 18
#define GrasslandBank 0

#define Grassland GrasslandPLN0
extern unsigned char GrasslandPLN0[];
extern unsigned char GrasslandPLN1[];

/* End of GRASSLAND.H */
