/*

 MAP_V1_1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define map_v1_1Bank 0

/* Super Gameboy palette 0 */
#define map_v1_1SGBPal0c0 6076
#define map_v1_1SGBPal0c1 8935
#define map_v1_1SGBPal0c2 6596
#define map_v1_1SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define map_v1_1SGBPal1c0 6076
#define map_v1_1SGBPal1c1 8935
#define map_v1_1SGBPal1c2 6596
#define map_v1_1SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define map_v1_1SGBPal2c0 6076
#define map_v1_1SGBPal2c1 8935
#define map_v1_1SGBPal2c2 6596
#define map_v1_1SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define map_v1_1SGBPal3c0 6076
#define map_v1_1SGBPal3c1 8935
#define map_v1_1SGBPal3c2 6596
#define map_v1_1SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define map_v1_1CGBPal0c0 21359
#define map_v1_1CGBPal0c1 23254
#define map_v1_1CGBPal0c2 17115
#define map_v1_1CGBPal0c3 19150

/* Gameboy Color palette 1 */
#define map_v1_1CGBPal1c0 6076
#define map_v1_1CGBPal1c1 8935
#define map_v1_1CGBPal1c2 6596
#define map_v1_1CGBPal1c3 5344

/* Gameboy Color palette 2 */
#define map_v1_1CGBPal2c0 6076
#define map_v1_1CGBPal2c1 8935
#define map_v1_1CGBPal2c2 6596
#define map_v1_1CGBPal2c3 5344

/* Gameboy Color palette 3 */
#define map_v1_1CGBPal3c0 6076
#define map_v1_1CGBPal3c1 8935
#define map_v1_1CGBPal3c2 6596
#define map_v1_1CGBPal3c3 5344

/* Gameboy Color palette 4 */
#define map_v1_1CGBPal4c0 6076
#define map_v1_1CGBPal4c1 8935
#define map_v1_1CGBPal4c2 6596
#define map_v1_1CGBPal4c3 5344

/* Gameboy Color palette 5 */
#define map_v1_1CGBPal5c0 6076
#define map_v1_1CGBPal5c1 8935
#define map_v1_1CGBPal5c2 6596
#define map_v1_1CGBPal5c3 5344

/* Gameboy Color palette 6 */
#define map_v1_1CGBPal6c0 6076
#define map_v1_1CGBPal6c1 8935
#define map_v1_1CGBPal6c2 6596
#define map_v1_1CGBPal6c3 5344

/* Gameboy Color palette 7 */
#define map_v1_1CGBPal7c0 6076
#define map_v1_1CGBPal7c1 8935
#define map_v1_1CGBPal7c2 6596
#define map_v1_1CGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char map_v1_1CGB[];
/* Start of tile array. */
extern unsigned char map_v1_1[];

/* End of MAP_V1_1.H */
