/*

 GRASSLAND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : map_v1_1.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Grassland_h_INCLUDE
#define __Grassland_h_INCLUDE

#define Grassland_labelWidth 20
#define Grassland_labelHeight 18
#define Grassland_labelBank 0

#define Grassland_label Grassland_labelPLN0
extern const unsigned char Grassland_labelPLN0[];
extern const unsigned char Grassland_labelPLN1[];

#endif

/* End of GRASSLAND.H */
