/*

 GTP.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define GTPBank 0

/* Super Gameboy palette 0 */
#define GTPSGBPal0c0 6076
#define GTPSGBPal0c1 8935
#define GTPSGBPal0c2 6596
#define GTPSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define GTPSGBPal1c0 6076
#define GTPSGBPal1c1 8935
#define GTPSGBPal1c2 6596
#define GTPSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define GTPSGBPal2c0 6076
#define GTPSGBPal2c1 8935
#define GTPSGBPal2c2 6596
#define GTPSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define GTPSGBPal3c0 6076
#define GTPSGBPal3c1 8935
#define GTPSGBPal3c2 6596
#define GTPSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define GTPCGBPal0c0 32767
#define GTPCGBPal0c1 1102
#define GTPCGBPal0c2 4513
#define GTPCGBPal0c3 12255

/* Gameboy Color palette 1 */
#define GTPCGBPal1c0 32767
#define GTPCGBPal1c1 5153
#define GTPCGBPal1c2 16483
#define GTPCGBPal1c3 31975

/* Gameboy Color palette 2 */
#define GTPCGBPal2c0 32767
#define GTPCGBPal2c1 11297
#define GTPCGBPal2c2 12684
#define GTPCGBPal2c3 116

/* Gameboy Color palette 3 */
#define GTPCGBPal3c0 32767
#define GTPCGBPal3c1 5153
#define GTPCGBPal3c2 2451
#define GTPCGBPal3c3 25269

/* Gameboy Color palette 4 */
#define GTPCGBPal4c0 6076
#define GTPCGBPal4c1 8935
#define GTPCGBPal4c2 6596
#define GTPCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define GTPCGBPal5c0 6076
#define GTPCGBPal5c1 8935
#define GTPCGBPal5c2 6596
#define GTPCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define GTPCGBPal6c0 6076
#define GTPCGBPal6c1 8935
#define GTPCGBPal6c2 6596
#define GTPCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define GTPCGBPal7c0 32767
#define GTPCGBPal7c1 4512
#define GTPCGBPal7c2 2468
#define GTPCGBPal7c3 8000
/* CGBpalette entries. */
extern unsigned char GTPCGB[];
/* Start of tile array. */
extern unsigned char GTP[];

/* End of GTP.H */
