/*

 MAP_V1_1.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __map_v1_1_h_INCLUDE
#define __map_v1_1_h_INCLUDE

/* Bank of tiles. */
#define map_v1_1_labelBank 0

/* Super Gameboy palette 0 */
#define map_v1_1_labelSGBPal0c0 6076
#define map_v1_1_labelSGBPal0c1 8935
#define map_v1_1_labelSGBPal0c2 6596
#define map_v1_1_labelSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define map_v1_1_labelSGBPal1c0 6076
#define map_v1_1_labelSGBPal1c1 8935
#define map_v1_1_labelSGBPal1c2 6596
#define map_v1_1_labelSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define map_v1_1_labelSGBPal2c0 6076
#define map_v1_1_labelSGBPal2c1 8935
#define map_v1_1_labelSGBPal2c2 6596
#define map_v1_1_labelSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define map_v1_1_labelSGBPal3c0 6076
#define map_v1_1_labelSGBPal3c1 8935
#define map_v1_1_labelSGBPal3c2 6596
#define map_v1_1_labelSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define map_v1_1_labelCGBPal0c0 21359
#define map_v1_1_labelCGBPal0c1 23254
#define map_v1_1_labelCGBPal0c2 17115
#define map_v1_1_labelCGBPal0c3 19150

/* Gameboy Color palette 1 */
#define map_v1_1_labelCGBPal1c0 6076
#define map_v1_1_labelCGBPal1c1 8935
#define map_v1_1_labelCGBPal1c2 6596
#define map_v1_1_labelCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define map_v1_1_labelCGBPal2c0 6076
#define map_v1_1_labelCGBPal2c1 8935
#define map_v1_1_labelCGBPal2c2 6596
#define map_v1_1_labelCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define map_v1_1_labelCGBPal3c0 6076
#define map_v1_1_labelCGBPal3c1 8935
#define map_v1_1_labelCGBPal3c2 6596
#define map_v1_1_labelCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define map_v1_1_labelCGBPal4c0 6076
#define map_v1_1_labelCGBPal4c1 8935
#define map_v1_1_labelCGBPal4c2 6596
#define map_v1_1_labelCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define map_v1_1_labelCGBPal5c0 6076
#define map_v1_1_labelCGBPal5c1 8935
#define map_v1_1_labelCGBPal5c2 6596
#define map_v1_1_labelCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define map_v1_1_labelCGBPal6c0 6076
#define map_v1_1_labelCGBPal6c1 8935
#define map_v1_1_labelCGBPal6c2 6596
#define map_v1_1_labelCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define map_v1_1_labelCGBPal7c0 6076
#define map_v1_1_labelCGBPal7c1 8935
#define map_v1_1_labelCGBPal7c2 6596
#define map_v1_1_labelCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char map_v1_1_labelCGB[];
/* Start of tile array. */
extern const unsigned char map_v1_1_label[];

#endif

/* End of MAP_V1_1.H */
