/*

 BACKG.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgWidth 40
#define backgHeight 18
#define backgBank 0

unsigned char windowmap[] =
{
  0x1B,0x10,0x19,0x14,0x1E
};